apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments
    spec:
      containers:
      - image: us-east1-docker.pkg.dev/microservices-nest/image-registry/payments-ms
        name: payments-ms
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVER
          value: "nats://nats"
        - name: SUCCESS_PAYMENT_URL
          value: "http://localhost:3003/payments/success"
        - name: CANCELLED_PAYMENT_URL
          value: "http://localhost:3003/payments/cancel"
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: STRIPE_WEBHOOK_SECRET
        resources: {}
status: {}

